#devopsdemo - pipeline

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: 'build'
    condition: succeeded()
    displayName: 'build-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'build process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet build
  
  - stage: 'test'
    condition: succeeded()
    dependsOn:
      - build
    displayName: 'test-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'test process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet test

  - stage: 'pack'
    condition: succeeded()
    dependsOn:
      - test
    displayName: 'pack-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'pack process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'Hello pack my old friend~~!'
  
  - stage: 'deploy'
    condition: succeeded()
    dependsOn:
      - test
    displayName: 'deploy-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'deploy process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'Hello deploy my old friend~~!'

trigger:
  branches:
    include:
      - master

variables:
  testVar: 'tuesday'